### ISSUE TITLE
template help files

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/Online-Help#78]
It would be nice if things like release version, etc. could always be up-to-date with the latest release, and so on so that they didn't get overly stale over time.

That seems somewhat like a tall-order (of manual tedious work) but it's not so much I don't think. If we templated our whole help repository with some key substitutions like _@CURRENT_RELEASE@_ (there are probably others we could use also), many of which could be auto-determined and then just periodically (nightly even) regenerated the help repo from the templates and produced a diff to be manually inspected and pushed the whole thing could be mostly automated. A diff and a push would only be necessary of course when a substituted item changes.

Think of this like greenkeeper for the docs -- keeping things up-to-date (mostly -- to whatever level of full automation we wanted) automatically.

This could be done very simply by naming any files that need substitutions done on them with a `.in` suffix, then run the following over the repo:

```bash
mv generated_content{,.old}
CURRENT_RELEASE=4.0.5.0 # this could be automatically determined from GitHub
FOO=foo
BAR=bar
find . -name \*.in | while read file; do
    sed -e "s/@CURRENT_RELEASE@/$CURRENT_RELEASE/g" \
        -e "s/@FOO@/$FOO/g" \
        -e "s/@BAR@/$BAR/g" \
      < $file > $file{%.in}
done
# regenerate content in generated_content
diff -ur generated_content{,.old,}
```

The list of substitution expressions in the `sed` grows 1:1 with the number of values we want to template into the help files.

**Comment by jgrund** [comment]
Wonder if jekyll has templating built-in
